spring.application.name=IAreceita

#Credencial do DB H2
spring.datasource.url=${DATA_BASE_URL};
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=${DATA_BASE_USER}
spring.datasource.password=${DATA_BASE_PASSWORD}

#Config JPA/Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true
spring.jpa.properties.hibernate.format_sql=true

#Config Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migrations

#Config gemini
gemini.url.base=https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash:generateContent
gemini.api.key=${GEMINI_API_KEY}